import type { ServiceCategory, ServiceProvider, ServiceReview } from './types';

export const serviceCategories: { id: ServiceCategory; label: string; icon: string }[] = [
  { id: 'plumber',      label: 'Plumbers',      icon: '🔧' },
  { id: 'electrician',  label: 'Electricians',   icon: '⚡' },
  { id: 'technician',   label: 'Technicians',    icon: '🖥️' },
  { id: 'ac_repair',    label: 'AC Repair',      icon: '❄️' },
  { id: 'carpenter',    label: 'Carpenters',     icon: '🪵' },
  { id: 'painter',      label: 'Painters',       icon: '🖌️' },
  { id: 'cleaner',      label: 'Cleaners',       icon: '🧹' },
  { id: 'welder',       label: 'Welders',        icon: '🔥' },
];

export const sampleServiceProviders: ServiceProvider[] = [
  {
    id: 'hassan-plumbing',
    name: 'Hassan Plumbing Services',
    category: 'plumber',
    description: 'Expert plumbing repairs, pipe installation, water heater setup, and emergency leak fixes across Hargeisa. Available 7 days a week.',
    phone: '+252 63 511 0001',
    whatsapp: '+252 63 511 0001',
    city: 'Hargeisa',
    address: 'Jigjiga Yar, Hargeisa',
    latitude: 9.5558,
    longitude: 44.0614,
    images: ['https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?q=80&w=1200'],
    rating: 4.8,
    review_count: 42,
    verified: true,
    years_experience: 12,
    price_range: '$10 – $80',
    available: true,
  },
  {
    id: 'nuur-electric',
    name: 'Nuur Electric Works',
    category: 'electrician',
    description: 'Licensed electrician for wiring, generator installation, solar panel setup, switchboard repair, and safety inspections.',
    phone: '+252 63 522 0002',
    whatsapp: '+252 63 522 0002',
    city: 'Hargeisa',
    address: 'Sha\'ab Area, Hargeisa',
    latitude: 9.5662,
    longitude: 44.0488,
    images: ['https://images.unsplash.com/photo-1621905251189-08b45d6a269e?q=80&w=1200'],
    rating: 4.9,
    review_count: 67,
    verified: true,
    years_experience: 15,
    price_range: '$15 – $120',
    available: true,
  },
  {
    id: 'tech-fix-hargeisa',
    name: 'Tech Fix Hargeisa',
    category: 'technician',
    description: 'Phone, laptop, TV, and appliance repair. Screen replacements, data recovery, software issues, and same-day service for most repairs.',
    phone: '+252 63 533 0003',
    whatsapp: '+252 63 533 0003',
    city: 'Hargeisa',
    address: 'Downtown Hargeisa',
    latitude: 9.5612,
    longitude: 44.0672,
    images: ['https://images.unsplash.com/photo-1581092795360-fd1ca04f0952?q=80&w=1200'],
    rating: 4.6,
    review_count: 89,
    verified: true,
    years_experience: 8,
    price_range: '$5 – $60',
    available: true,
  },
  {
    id: 'cool-air-ac',
    name: 'Cool Air AC Services',
    category: 'ac_repair',
    description: 'Air conditioner installation, servicing, gas refill, and emergency repairs. All AC brands covered including Samsung, LG, and Gree.',
    phone: '+252 63 544 0004',
    whatsapp: '+252 63 544 0004',
    city: 'Hargeisa',
    address: 'Airport Road, Hargeisa',
    latitude: 9.5471,
    longitude: 44.0882,
    images: ['https://images.unsplash.com/photo-1581094794329-c8112a89af12?q=80&w=1200'],
    rating: 4.7,
    review_count: 31,
    verified: true,
    years_experience: 10,
    price_range: '$20 – $150',
    available: true,
  },
  {
    id: 'abdi-carpentry',
    name: 'Abdi Carpentry & Furniture',
    category: 'carpenter',
    description: 'Custom furniture, door and window frames, cabinet making, and wood repairs. Quality craftsmanship at fair prices.',
    phone: '+252 63 555 0005',
    whatsapp: '+252 63 555 0005',
    city: 'Hargeisa',
    address: 'Industrial Area, Hargeisa',
    latitude: 9.5502,
    longitude: 44.0755,
    images: ['https://images.unsplash.com/photo-1588854337115-1c67d9247e4d?q=80&w=1200'],
    rating: 4.5,
    review_count: 28,
    verified: false,
    years_experience: 20,
    price_range: '$30 – $500',
    available: true,
  },
  {
    id: 'clean-pro-services',
    name: 'CleanPro Home Services',
    category: 'cleaner',
    description: 'Professional home and office cleaning. Deep cleaning, post-construction cleanup, and regular weekly/monthly cleaning packages.',
    phone: '+252 63 566 0006',
    whatsapp: '+252 63 566 0006',
    city: 'Hargeisa',
    address: 'Maka Al Mukarama, Hargeisa',
    latitude: 9.5609,
    longitude: 44.0651,
    images: ['https://images.unsplash.com/photo-1581578731548-c64695cc6952?q=80&w=1200'],
    rating: 4.4,
    review_count: 19,
    verified: true,
    years_experience: 5,
    price_range: '$15 – $100',
    available: true,
  },
  {
    id: 'maxamed-painter',
    name: 'Maxamed Painting & Decor',
    category: 'painter',
    description: 'Interior and exterior painting, wall preparation, texture finishes, and decorative design for homes and commercial properties.',
    phone: '+252 63 577 0007',
    whatsapp: '+252 63 577 0007',
    city: 'Berbera',
    address: 'Berbera Port Area',
    latitude: 10.4328,
    longitude: 45.0138,
    images: ['https://images.unsplash.com/photo-1562259949-e8e7689d7828?q=80&w=1200'],
    rating: 4.3,
    review_count: 14,
    verified: false,
    years_experience: 7,
    price_range: '$20 – $200',
    available: true,
  },
  {
    id: 'welding-king-borama',
    name: 'Welding King Borama',
    category: 'welder',
    description: 'Metal gates, security doors, window grills, staircase railings, and custom metalwork. Workshop and on-site welding available.',
    phone: '+252 63 588 0008',
    whatsapp: '+252 63 588 0008',
    city: 'Borama',
    address: 'Central Market, Borama',
    latitude: 9.9321,
    longitude: 43.1854,
    images: ['https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?q=80&w=1200'],
    rating: 4.6,
    review_count: 22,
    verified: true,
    years_experience: 18,
    price_range: '$25 – $300',
    available: true,
  },
];

export const sampleServiceReviews: ServiceReview[] = [
  {
    id: 'rev-1',
    provider_id: 'hassan-plumbing',
    reviewer_name: 'Faadumo A.',
    reviewer_phone: null,
    rating: 5,
    comment: 'Hassan fixed our broken pipe within 2 hours of calling. Very professional and fair price. Highly recommend!',
    created_at: '2024-11-10T09:00:00Z',
  },
  {
    id: 'rev-2',
    provider_id: 'hassan-plumbing',
    reviewer_name: 'Maxamed H.',
    reviewer_phone: null,
    rating: 5,
    comment: 'Installed a new water heater perfectly. Cleaned up after the work too. Will definitely call again.',
    created_at: '2024-11-05T14:30:00Z',
  },
  {
    id: 'rev-3',
    provider_id: 'nuur-electric',
    reviewer_name: 'Caisha M.',
    reviewer_phone: null,
    rating: 5,
    comment: 'Wired our whole office building. Nuur is very knowledgeable and the work passed inspection with no issues.',
    created_at: '2024-11-12T11:00:00Z',
  },
  {
    id: 'rev-4',
    provider_id: 'tech-fix-hargeisa',
    reviewer_name: 'Cabdirashid I.',
    reviewer_phone: null,
    rating: 4,
    comment: 'Fixed my cracked iPhone screen same day. Good price, only took 1 hour.',
    created_at: '2024-11-08T16:00:00Z',
  },
  {
    id: 'rev-5',
    provider_id: 'cool-air-ac',
    reviewer_name: 'Warsan Y.',
    reviewer_phone: null,
    rating: 5,
    comment: 'AC was not cooling at all. They came the next morning and fixed it quickly. Very satisfied.',
    created_at: '2024-11-01T10:00:00Z',
  },
];
